name: registry
home: https://github.com/deisthree/registry
version: <Will be populated by the ci before publishing the chart>
description: Docker registry for Deis Workflow.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
